# vim:ff=unix ts=2 sw=2 ai expandtab
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^tests/fixtures/fail/.*$
        additional_dependencies:
          - prettier@3.2.5
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: forbid-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c 'pip install -e . && pytest'
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [pytest, pytest-cov, pyyaml>=5.1]
