- id: forbid-secrets
  name: Check for unencrypted Kubernetes secrets in manifests
  description: "Forbid files containing unencrypted Kubernetes secrets to be commited"
  entry: forbid_secrets
  language: python
  types_or: [yaml, json]
  files: \.(yaml|yml|json|enc\.yaml)$